export const ADD_TO_CART = 'ADD_TO_CART'

export const REMOVE_FROM_CART = 'REMOVE_FROM_CART'

export const INCREMENT = 'INCREMENT'

export const DECREMENT = 'DECREMENT'

export const ADD_REVIEW_ITEM = 'ADD_REVIEW_ITEM'

export const SET_REVIEWFORM_DATA = 'SET_REVIEWFORM_DATA'
